import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Zap, ArrowLeft } from "lucide-react";

const Section = ({ title, children }) => (
  <div className="mb-8">
    <h2 className="text-lg font-bold text-slate-900 font-heading mb-3 border-b border-slate-100 pb-2">{title}</h2>
    <div className="space-y-2 text-slate-600 text-sm leading-relaxed">{children}</div>
  </div>
);

export default function TermsAndPrivacy() {
  const [tab, setTab] = useState("terms");
  const navigate = useNavigate();

  const goBack = () => {
    if (window.history.length > 1) navigate(-1);
    else navigate("/");
  };

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <nav className="bg-white border-b border-slate-200 px-4 sm:px-6 py-3 pt-[calc(env(safe-area-inset-top)+0.75rem)] flex items-center justify-between gap-3">
        <button onClick={goBack} className="min-h-[44px] flex items-center gap-2 rounded-xl px-2 -ml-2 text-slate-600 hover:bg-slate-100 active:bg-slate-200 transition-colors">
          <ArrowLeft className="w-4 h-4" />
          <span className="text-sm font-medium">Back</span>
        </button>
        <Link to="/" className="flex items-center gap-2 min-w-0">
          <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center shrink-0">
            <Zap className="w-4 h-4 text-white" />
          </div>
          <span className="font-bold text-slate-900 font-heading truncate">DebateLab</span>
        </Link>
        <span className="text-slate-500 text-sm hidden sm:inline">Legal</span>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-12">
        {/* Tab switcher */}
        <div className="flex gap-2 mb-8 bg-white border border-slate-200 rounded-xl p-1 w-fit">
          <button onClick={() => setTab("terms")}
            className={`px-5 py-2 rounded-lg text-sm font-medium transition-all ${tab === "terms" ? "bg-primary text-white" : "text-slate-600 hover:bg-slate-50"}`}>
            Terms of Service
          </button>
          <button onClick={() => setTab("privacy")}
            className={`px-5 py-2 rounded-lg text-sm font-medium transition-all ${tab === "privacy" ? "bg-primary text-white" : "text-slate-600 hover:bg-slate-50"}`}>
            Privacy Policy
          </button>
        </div>

        <div className="bg-white rounded-2xl border border-slate-200 p-8 shadow-sm">
          {tab === "terms" ? (
            <>
              <h1 className="text-2xl font-bold text-slate-900 font-heading mb-1">Terms of Service</h1>
              <p className="text-slate-400 text-xs mb-8">Last updated: June 2025</p>

              <Section title="1. Acceptance of Terms">
                <p>By creating an account or using DebateLab ("the Platform"), you agree to these Terms of Service. If you do not agree, do not use the Platform.</p>
                <p>Users will be notified of material changes to these Terms and the Privacy Policy via email or in-app notification. Continued use of the Platform after notification constitutes acceptance of updated terms.</p>
              </Section>

              <Section title="2. Description of Service">
                <p>DebateLab is an AI-powered competitive debate preparation platform supporting Parliamentary Debate, Public Forum, Model UN, and Model Congress formats.</p>
                <p>Core DebateLab features are intended to remain free. Certain premium features may be introduced in the future with advance notice to users.</p>
              </Section>

              <Section title="3. No Liability for Debate Results">
                <p><strong>IMPORTANT:</strong> DebateLab, its creators, employees, contributors, and any affiliated persons are <strong>not liable for any debate results, competition outcomes, wins, losses, speaker points, or tournament placements</strong> of any kind.</p>
                <p>All content generated by DebateLab (contentions, evidence, position papers, rebuttals, etc.) is AI-generated for educational and preparation purposes only. You use this content entirely at your own risk.</p>
                <p>DebateLab does not guarantee the accuracy, completeness, or appropriateness of any AI-generated content for any particular debate, tournament, or competition. Always verify evidence and arguments independently before use in competition.</p>
              </Section>

              <Section title="4. No Legal Action">
                <p>By using DebateLab, you agree that you will not bring any legal action, lawsuit, or claim against DebateLab, its operators, developers, contributors, or affiliated persons arising from your use of the Platform, including but not limited to debate outcomes, AI-generated content, data loss, or service interruption.</p>
                <p>This Platform is provided "as is" without warranties of any kind, express or implied.</p>
              </Section>

              <Section title="5. User Conduct">
                <p>You agree to use DebateLab only for lawful, educational, and debate-related purposes. The following are strictly prohibited:</p>
                <ul className="list-disc list-inside space-y-1 ml-2">
                  <li>Explicit sexual content of any kind</li>
                  <li>Harassment, bullying, or targeted abuse of other users</li>
                  <li>Hate speech, discrimination, or content promoting violence</li>
                  <li>Attempting to access other users' accounts or data</li>
                  <li>Using the Platform to circumvent laws or regulations</li>
                  <li>Impersonating other users or public figures</li>
                </ul>
                <p className="mt-2"><strong>Content violations:</strong> Users who post explicit sexual content will be permanently banned. Other violations receive a first warning, a final warning, and then a permanent ban for repeated offenses.</p>
                <p>Users can report objectionable content and block abusive users from the forum. Blocking immediately removes that user's content from the blocker’s feed and creates a moderation report for review.</p>
                <p>Moderation reports are reviewed by the developer within 24 hours. Content confirmed as objectionable may be removed, and the user who posted it may be warned, restricted, or permanently banned.</p>
              </Section>

              <Section title="6. Account Termination">
                <p>DebateLab reserves the right to suspend or permanently ban any account for violations of these Terms. All bans are logged and may be reviewed by contacting DebateLab@outlook.com.</p>
                <p>You may delete your account at any time from the Profile page. Account deletion is permanent and removes your personal data within 30 days, subject to legal retention requirements.</p>
              </Section>

              <Section title="7. Argument Difficulty Levels">
                <p>For transparency, contention difficulty levels are defined as follows:</p>
                <ul className="list-disc list-inside space-y-1 ml-2">
                  <li><strong>Beginner:</strong> Simple, direct arguments requiring minimal debate experience. Uses clear logical structures accessible to new debaters.</li>
                  <li><strong>Intermediate:</strong> Arguments incorporating statistics and strategic framing. Requires basic familiarity with debate conventions.</li>
                  <li><strong>Advanced:</strong> Complex, multi-layered arguments requiring strong evidence and strategic positioning. Tournament-competitive.</li>
                  <li><strong>Expert:</strong> Highly technical arguments using sophisticated philosophical frameworks and cutting-edge research. For elite competition.</li>
                </ul>
              </Section>

              <Section title="8. Contact">
                <p>For any questions, support, or concerns: <a href="mailto:DebateLab@outlook.com" className="text-primary hover:underline font-medium">DebateLab@outlook.com</a></p>
              </Section>
            </>
          ) : (
            <>
              <h1 className="text-2xl font-bold text-slate-900 font-heading mb-1">Privacy Policy</h1>
              <p className="text-slate-400 text-xs mb-8">Last updated: June 2025</p>

              <Section title="1. Information We Collect">
                <p>We collect information you provide directly:</p>
                <ul className="list-disc list-inside space-y-1 ml-2">
                  <li>Account information (email address, display name, school)</li>
                  <li>Content you create (contentions, notes, AI conversations, tournament records)</li>
                  <li>Usage data (features used, time spent, practice session results)</li>
                </ul>
              </Section>

              <Section title="2. Data Security">
                <p>All data transmitted to and from DebateLab is encrypted in transit using TLS. Data stored on our servers is encrypted at rest. We use industry-standard security practices to protect your information.</p>
                <p>While we take security seriously, no system is 100% secure. We encourage you to use a strong, unique password.</p>
              </Section>

              <Section title="3. How We Use Your Data">
                <p>We use your data to:</p>
                <ul className="list-disc list-inside space-y-1 ml-2">
                  <li>Provide and improve the DebateLab platform</li>
                  <li>Generate personalized AI coaching and recommendations</li>
                  <li>Send you important platform updates and notifications</li>
                  <li>Ensure platform safety and enforce our Terms of Service</li>
                </ul>
              </Section>

              <Section title="4. Data Sharing">
                <p><strong>We do not sell your personal data.</strong> We do not share your personal data with third parties except in the following limited circumstances:</p>
                <ul className="list-disc list-inside space-y-1 ml-2">
                  <li>With your explicit consent</li>
                  <li>For customer service and technical support purposes</li>
                  <li>To ensure platform safety and address security threats</li>
                  <li>To protect the privacy and safety of users</li>
                  <li>When required by law, court order, or valid legal process</li>
                </ul>
              </Section>

              <Section title="5. AI-Generated Content">
                <p>When you use AI features, your prompts (resolutions, topics, countries) are sent to AI providers to generate content. This data is used solely for generating your requested content and is not used to train AI models.</p>
              </Section>

              <Section title="6. Data Retention & Deletion">
                <p>We retain your data for as long as your account is active. When you delete your account, your personal data is removed within 30 days. Some data may be retained for legal compliance, fraud prevention, or safety purposes.</p>
              </Section>

              <Section title="7. Your Rights">
                <p>You have the right to access, correct, or delete your personal data. Contact <a href="mailto:DebateLab@outlook.com" className="text-primary hover:underline">DebateLab@outlook.com</a> to exercise these rights.</p>
              </Section>

              <Section title="8. Cookies">
                <p>We use essential cookies to maintain your login session. We do not use advertising cookies or third-party tracking cookies.</p>
              </Section>

              <Section title="9. Contact">
                <p>Privacy questions: <a href="mailto:DebateLab@outlook.com" className="text-primary hover:underline font-medium">DebateLab@outlook.com</a></p>
              </Section>
            </>
          )}
        </div>

        <p className="text-center text-slate-400 text-xs mt-8">
          <Link to="/" className="hover:text-primary transition-colors">← Back to DebateLab</Link>
          {" · "}
          <a href="mailto:DebateLab@outlook.com" className="hover:text-primary transition-colors">DebateLab@outlook.com</a>
        </p>
      </div>
    </div>
  );
}